protocol=http
host=spring-app
port=8080

threads=5
rampUp=10
loops=1
onSampleError=continue

adminEmail=admin@suaempresa.com
adminPassword=admin123
userPassword=senha12345

summariser.name=summary
jmeter.save.saveservice.output_format=csv
jmeter.save.saveservice.response_code=true
jmeter.save.saveservice.response_message=true
jmeter.save.saveservice.successful=true
jmeter.save.saveservice.thread_name=true
jmeter.save.saveservice.time=true
jmeter.save.saveservice.latency=true
jmeter.save.saveservice.bytes=true
jmeter.save.saveservice.sent_bytes=true
jmeter.save.saveservice.label=true
